// <auto-generated />
using System;
using HorizonteAzulApi.Models.HorizonteAzul;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HorizonteAzulApi.Migrations
{
    [DbContext(typeof(HorizonteAzulContext))]
    [Migration("20260107235756_MigracaoInicial")]
    partial class MigracaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HorizonteAzulApi.Models.HorizonteAzul.Sessao", b =>
                {
                    b.Property<int>("SessaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessaoId"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("SessaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Sessao");
                });

            modelBuilder.Entity("HorizonteAzulApi.Models.HorizonteAzul.SituacaoUsuario", b =>
                {
                    b.Property<int>("SituacaoUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SituacaoUsuarioId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SituacaoUsuarioId");

                    b.ToTable("SituacaoUsuario");
                });

            modelBuilder.Entity("HorizonteAzulApi.Models.HorizonteAzul.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimoAcesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SituacaoUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.HasIndex("SituacaoUsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("HorizonteAzulApi.Models.HorizonteAzul.Sessao", b =>
                {
                    b.HasOne("HorizonteAzulApi.Models.HorizonteAzul.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HorizonteAzulApi.Models.HorizonteAzul.Usuario", b =>
                {
                    b.HasOne("HorizonteAzulApi.Models.HorizonteAzul.SituacaoUsuario", "SituacaoUsuario")
                        .WithMany()
                        .HasForeignKey("SituacaoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SituacaoUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
